--- include/linux/Kbuild
+++ include/linux/Kbuild
@@ -406,3 +406,13 @@
 header-y += android_pmem.h
 header-y += msm_audio_wma.h
 header-y += msm_audio_wmapro.h
+header-y += msm_audio_mvs.h
+header-y += msm_audio_qcp.h
+header-y += msm_audio_amrnb.h
+header-y += msm_audio_voicememo.h
+header-y += msm_ipc.h
+header-y += msm_charm.h
+header-y += tzcom.h
+header-y += qcedev.h
+header-y += idle_stats_device.h
+header-y += genlock.h
